// <auto-generated />
using System;
using ClientAccountAPI.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClientAccountAPI.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ClientAccountAPI.Web.Model.AccountHistory", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("accountNumber")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("transactionAmmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("transactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("AccountHistory");
                });

            modelBuilder.Entity("ClientAccountAPI.Web.Model.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("accountBalance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("accountNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("accountTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("creationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("customerNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("ClientAccountAPI.Web.Model.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardIdentificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Income")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
